theme: jekyll-theme-cayman
title: Free Share Open

# your name show in footer
author: laocai


navbar-links:
  About Me: "about_me"
  Resource: "None"

# exclude these files from production site
exclude:
  - README.md
  - LICENSE
